# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "clasrip"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brendan Molloy"]
  s.date = "2012-02-26"
  s.description = "A scraper for classification.gov.au"
  s.email = "brendan@bbqsrc.net"
  s.executables = ["clasrip"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/clasrip",
    "clasrip.gemspec",
    "lib/clasrip.rb",
    "lib/clasrip/sql.rb",
    "test/helper.rb",
    "test/test_clasrip.rb"
  ]
  s.homepage = "http://github.com/bbqsrc/clasrip"
  s.licenses = ["CC0"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A scraper for classification.gov.au"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<data_mapper>, [">= 1.2.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_dependency(%q<data_mapper>, [">= 1.2.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
    s.add_dependency(%q<data_mapper>, [">= 1.2.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

